name: Test Gestion Produits

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Voir la structure du projet
        run: |
          ls -la

      - name: Voir les fichiers reçus par GitHub
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -type f

      - name: Vérifier index.html
        run: |
          test -f index.html
          echo "index.html trouvé"

      - name: Vérifier les fichiers principaux
        run: |
          test -f main.js
          test -f firebase.js
          echo "Structure OK"
